social_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  # Body ---------------------------------------
  Waist_Roll_position:
    type: position_controllers/JointPositionController
    joint: Waist_Roll
    pid: {p: 1000.0, i: 1.0, d: 10.0}
    
  Waist_Pitch_position:
    type: position_controllers/JointPositionController
    joint: Waist_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  # Head ---------------------------------------
  Head_Yaw_position:
    type: position_controllers/JointPositionController
    joint: Head_Yaw
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  Head_Pitch_position:
    type: position_controllers/JointPositionController
    joint: Head_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  # left arm ---------------------------------------
  LShoulder_Pitch_position:
    type: position_controllers/JointPositionController
    joint: LShoulder_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  LShoulder_Roll_position:
    type: position_controllers/JointPositionController
    joint: LShoulder_Roll
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  LElbow_Pitch_position:
    type: position_controllers/JointPositionController
    joint: LElbow_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  LElbow_Yaw_position:
    type: position_controllers/JointPositionController
    joint: LElbow_Yaw
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  LWrist_Pitch_position:
    type: position_controllers/JointPositionController
    joint: LWrist_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  LFinger_position:
    type: position_controllers/JointPositionController
    joint: LFinger
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  # right arm ---------------------------------------
  RShoulder_Pitch_position:
    type: position_controllers/JointPositionController
    joint: RShoulder_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  RShoulder_Roll_position:
    type: position_controllers/JointPositionController
    joint: RShoulder_Roll
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  RElbow_Pitch_position:
    type: position_controllers/JointPositionController
    joint: RElbow_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  RElbow_Yaw_position:
    type: position_controllers/JointPositionController
    joint: RElbow_Yaw
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  RWrist_Pitch_position:
    type: position_controllers/JointPositionController
    joint: RWrist_Pitch
    pid: {p: 1000.0, i: 1.0, d: 10.0}

  RFinger_position:
    type: position_controllers/JointPositionController
    joint: RFinger
    pid: {p: 1000.0, i: 1.0, d: 10.0}
